/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

export const WITTY_LOADING_PHRASES = [
  'Thinking through the next step…',
  'Reading the room and the repository…',
  'Tracing the important details…',
  'Checking assumptions…',
  'Connecting the context…',
  'Working through the edge cases…',
  'Following the evidence…',
  'Keeping the terminal warm…',
  'Turning context into a plan…',
  'Looking for the smallest sound change…',
  'Making the pieces fit…',
  'Preparing a useful response…',
  'One careful step at a time…',
  'Resolving the tricky parts…',
  'Almost ready…',
  'Giving the tokens room to breathe…',
  'Negotiating with the edge cases…',
  'Untangling a particularly thoughtful knot…',
  'Keeping one eye on the context window…',
  'Finding the signal in the syntax…',
  'Turning uncertainty into useful questions…',
  'Taking the scenic route through the call stack…',
  'Making every token earn its place…',
  'Checking whether the simple answer is actually simple…',
  'Holding the context together…',
  'Listening for what the logs are not saying…',
  'Sorting the clues by usefulness…',
  'Looking around the next corner case…',
  'Keeping the sharp edges away from production…',
  'Reading between the stack frames…',
  'Asking the types for a second opinion…',
  'Letting the better approach catch up…',
  'Finding a clean seam in the problem…',
  'Reducing surprise, one branch at a time…',
  'Checking that the happy path has company…',
  'Making the invisible state visible…',
  'Following the data all the way through…',
  'Looking for the bug behind the bug…',
  'Giving the terminal something worth waiting for…',
  'Balancing clarity and momentum…',
  'Keeping the plan smaller than the problem…',
  'Finding the shortest path that stays correct…',
  'Checking the boundary before crossing it…',
  'Putting the pieces in dependency order…',
  'Leaving fewer mysteries for future us…',
  'Turning a rough idea into a stable interface…',
  'Looking for duplicated responsibility…',
  'Making room for the next turn…',
  'Keeping the useful parts and dropping the baggage…',
  'Tracing the shape of the answer…',
  'Checking whether the abstraction has earned its name…',
  'Teaching the details to cooperate…',
  'Preparing a response with fewer loose ends…',
  'Keeping the output human-sized…',
  'Making progress without waking the dragons…',
  'Waiting for the last puzzle piece to click…',
  'Polishing the path, not just the destination…',
  'Checking the contract from both sides…',
  'Turning terminal time into thinking time…',
  'Nearly there, with the edges accounted for…',
  'Looking for the commit that gets everyone home early…',
  'Convincing the tests to finish before dinner…',
  'Trying to leave future us an easier morning…',
  'Reducing tomorrow’s stand-up update…',
  'Checking whether this bug observes office hours…',
  'Saving one more developer from a late-night rollback…',
  'Making the build less dramatic than the group chat…',
  'Helping CI find its happy place…',
  'Racing the coffee before it gets cold…',
  'Finding the fix with the smallest overtime budget…',
  'Turning “quick change” into an actually quick change…',
  'Making Friday deployment slightly less adventurous…',
  'Checking if the flaky test has calmed down yet…',
  'Asking the compiler to use its indoor voice…',
  'Giving the linter one fewer opinion to share…',
  'Closing tabs on the road to going home…',
  'Converting one TODO into one DONE…',
  'Keeping the diff small and the evening free…',
  'Searching for a solution that survives code review…',
  'Making this easier to explain at stand-up…',
  'Checking whether lunch improved the algorithm…',
  'Helping the branch earn its merge button…',
  'Trying not to schedule a meeting with the debugger…',
  'Giving the rubber duck a moment to think…',
  'Removing one reason to open the laptop tonight…',
  'Finding a clean exit before the next calendar alert…',
  'Keeping production quiet enough for an early evening…',
  'Preparing a diff that reviewers can finish before tea…',
  'Making the last five percent take less than half the day…',
  'Almost ready to call this a productive workday…',
];

export const INFORMATIVE_TIPS = [
  // Settings
  'Choose an editor, enable Vim mode, or tune prompt completion with /settings…',
  'Change the active color theme with /theme…',
  'Define custom themes in settings.json…',
  'Choose whether reasoning is expanded, automatic, or hidden in /settings…',
  'Hide the footer, cwd, model, tips, or window title in /settings…',
  'Show memory usage or source line numbers in /settings…',
  'Use the alternate screen buffer to preserve your shell scrollback…',
  'Tune incremental rendering, the spinner, and loading phrases in /settings…',
  'Enable screen reader mode in /settings for a linear layout…',
  'Configure header art and layout in settings.json…',
  'Control gitignore-aware and fuzzy @-file search in /settings…',
  'Enable an interactive PTY or ANSI color for local shell commands in /settings…',
  'Configure shell environment redaction in /settings…',
  'Set advanced DNS ordering or project .env exclusions in settings.json…',
  'Enable OSC 52 paste for remote terminals in /settings…',

  // DSH and input
  'Select the active DSH model with /model…',
  'Start a fresh DSH Session with /new…',
  'Browse persisted DSH Sessions with /sessions…',
  'Resume a known DSH Session with /resume…',
  'Attach an image or expand text context with an @-file reference…',
  'Accept an AI prompt completion with Tab…',
  'Cancel the active turn with Ctrl+C, or press Ctrl+C while idle to exit…',
  'Toggle shell mode by typing ! in an empty prompt…',
  'Search prompt history with Ctrl+R…',
  'Navigate prompt history with Up/Down or Ctrl+P/Ctrl+N…',

  // Keyboard
  'Close dialogs and suggestions with Esc…',
  'Exit on an empty prompt with Ctrl+D…',
  'Clear the screen with Ctrl+L…',
  'Toggle detailed error information with F12…',
  'Toggle the todo tray with Ctrl+T…',
  'Toggle raw Markdown rendering with Alt+M…',
  'Insert a newline with a backslash followed by Enter…',
  'Open the current prompt in your editor with Ctrl+X…',
  'Paste text or an image from the clipboard with Ctrl+V…',
  'Undo with Ctrl+Z and redo with Ctrl+Shift+Z…',
  'Clear a non-empty prompt by pressing Esc twice…',
  'Open command help with /help…',
];
